config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :communities do
    resources :posts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'public#index'
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :posts
  has_many :communities
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :account
  has_many :posts
  validates_presence_of :url, :name, :rules
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  belongs_to :community
  validates_presence_of :title, :body, :account_id, :community_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, except: %i[index show]
  before_action :set_community, only: [:show]
  def index
    @communities = Community.all
  end

  def show
    @posts = @community.posts
  end

  def create
    @community = Community.new community_values
    @community.account_id = current_account.id
    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end

  def new
    @community = Community.new
  end

  private

  def set_community
    @community = Community.find(params[:id])
  end

  def community_values
    params.require(:community).permit(:name, :url, :rules)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: %i[index show]
  before_action :set_post, only: [:show]
  def index
    @posts = Post.all
  end
  
  def show; end
  
  def create
    @post = Post.new post_values
    @post.account_id = current_account.id
    @post.community_id = params[:community_id]
    if @post.save
      redirect_to community_path(@post.community_id)
    else
      @community = Community.find(params[:community_id])
      render :new
    end
  end
  
  def new
    @community = Community.find(params[:community_id])
    @post = Post.new
    @post.community_id = params[:community_id]
  end
  
  private
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_values
    params.require(:post).permit(:title, :body)
  end
end
  

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
    @communities = Community.all.limit(5)
    @posts = Post.order(id: :desc).limit(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/views/communities/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for @community do |form| %>
      <div class="form-group">
        <%= label_tag :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :url %>
        <%= form.text_field :url, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :rules %>
        <%= form.text_area :rules, class: "form-control" %>
      </div>
      <%= form.submit "Submit", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/communities/index.html.erb
<% if account_signed_in? %>
  <div class="float-end">
    <%= link_to "Create new Community!", new_community_path, class: "btn btn-outline-primary"%>
  </div>
<% end %>
<% if @communities.size > 0%>
  <% @communities.each do |community|%>
    <div class="card">
      <h3><%= link_to community.name, community  %></h3>
      <%= simple_format community.rules %>
    </div>
  <% end %>
<% else %>
  <p>No communities to display!</p>
<% end %>

app/views/communities/new.html.erb
<h2>New Community!</h2>
<%= render partial: "form" %>

app/views/communities/show.html.erb
<%= link_to "Create New Post", new_community_post_path(@community), class: "btn btn-primary float-end" %>
<%= @community.name %>
<% @posts.each do |post|%>
  <h4><%= link_to post.title, community_post_path(@community, post) %></h4>
  <p></p>
  <%= truncate post.body, length: 200 %></p>
<% end %>
<small>
  <%= simple_format @community.rules %>
</small>

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3 border-bottom pb-3 mb-4">
      <div class="float-end">
        <% if account_signed_in? %>
          <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "btn btn-outline-primary" %>
        <% else %>
          <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
          <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
      <h3><%= link_to "Reddit Clone", root_path %></h3>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: "layouts/header" %>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_for [@community, @post] do |form| %>
      <div class="form-group">
        <%= label_tag :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :body %>
        <%= form.text_area :body, class: "form-control" %>
      </div>
      <%= form.submit "Submit", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render partial: "form" %>

app/views/posts/new.html.erb
<h2>New Posts</h2>
<%= render partial: "form" %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<%= simple_format @post.body %>